OTS

diff --git a/files/usr/local/bin/onetimesecret-manager b/files/usr/local/bin/onetimesecret-manager
--- a/files/usr/local/bin/onetimesecret-manager
+++ b/files/usr/local/bin/onetimesecret-manager
@@ -1,28 +1,46 @@
 #!/bin/bash
 
+CONFIG_FILE="$HOME/.config/onetimesecret"
+OTS_BASE_URL="https://eu.onetimesecret.com"
+OTS_TTL=1209600
+
 _setup() {
-	OTS_CREDENTIALS=`echo -e "  Introduce tus credenciales de One Time Secret\n  usando el formato usuario@correo.com:APIKEY" | gxmessage -title "One Time Secret" -name "ONETIMESECRET_MANAGER" -center -borderless -ontop -sticky -font "sans 14" -wrap -buttons "GTK_STOCK_OK:0" -entry -geometry 512x180 -file -`
-	[ ! -z "$OTS_CREDENTIALS" ] && echo $OTS_CREDENTIALS > $HOME/.config/onetimesecret || exit 1
+	OTS_CREDENTIALS=$(echo -e "  Introduce tus credenciales de One Time Secret\n  usando el formato usuario@correo.com:APIKEY" | gxmessage -title "One Time Secret" -name "ONETIMESECRET_MANAGER" -center -borderless -ontop -sticky -font "sans 14" -wrap -buttons "GTK_STOCK_OK:0" -entry -geometry 512x180 -file -)
+	[ -z "$OTS_CREDENTIALS" ] && exit 1
+	echo "$OTS_CREDENTIALS" > "$CONFIG_FILE"
 }
 
 _share() {
 	[ -z "$1" ] && exit 1
-	[ ! -f $HOME/.config/onetimesecret ] && _setup
-	OTS_CREDENTIALS=`head -1 $HOME/.config/onetimesecret`
-	SECRET_KEY=`curl -s -u "$OTS_CREDENTIALS" -d "secret=$1&ttl=1209600" https://next.onetimesecret.com/api/v1/share | jq -r .secret_key`
-	[ -z "SECRET_KEY" ] && exit 1
-	echo -n "https://next.onetimesecret.com/secret/$SECRET_KEY"
+	[ ! -f "$CONFIG_FILE" ] && _setup
+	OTS_CREDENTIALS=$(head -1 "$CONFIG_FILE")
+
+	RESPONSE=$(curl -s -u "$OTS_CREDENTIALS" \
+		--data-urlencode "secret=$1" \
+		-d "ttl=$OTS_TTL" \
+		"$OTS_BASE_URL/api/v1/share")
+
+	SECRET_KEY=$(echo "$RESPONSE" | jq -r '.secret_key')
+
+	if [ -z "$SECRET_KEY" ] || [ "$SECRET_KEY" = "null" ]; then
+		ERROR_MSG=$(echo "$RESPONSE" | jq -r '.message // "Error desconocido"')
+		notify-send -i dialog-error "<b>One Time Secret</b>" "Error: $ERROR_MSG"
+		exit 1
+	fi
+
+	echo -n "$OTS_BASE_URL/secret/$SECRET_KEY"
 }
 
 _shareFromInput() {
-	SECRET_MESSAGE=`echo -e "  Introduce el secreto. Si nececitas más de\n  una línea, comparte desde el portapapeles." | gxmessage -title "One Time Secret" -name "ONETIMESECRET_MANAGER" -center -borderless -ontop -sticky -font "sans 14" -wrap -buttons "GTK_STOCK_OK:0" -entry -geometry 512x180 -file -`
+	SECRET_MESSAGE=$(echo -e "  Introduce el secreto. Si necesitas más de\n  una línea, comparte desde el portapapeles." | gxmessage -title "One Time Secret" -name "ONETIMESECRET_MANAGER" -center -borderless -ontop -sticky -font "sans 14" -wrap -buttons "GTK_STOCK_OK:0" -entry -geometry 512x180 -file -)
 	[ -z "$SECRET_MESSAGE" ] && exit 1
 	_share "$SECRET_MESSAGE" | xclip -selection clipboard
 	notify-send -i password "<b>One Time Secret</b>" "El secreto ha sido copiado al portapapeles"
 }
 
 _shareFromClipboard() {
-	SECRET_MESSAGE=`xclip -o -selection clipboard`
+	SECRET_MESSAGE=$(xclip -o -selection clipboard)
+	[ -z "$SECRET_MESSAGE" ] && exit 1
 	_share "$SECRET_MESSAGE" | xclip -selection clipboard
 	notify-send -i password "<b>One Time Secret</b>" "El secreto ha sido copiado al portapapeles"
 }
@@ -35,3 +53,4 @@ if [ $# -gt 0 ]; then
 		shareFromClipboard) _shareFromClipboard ;;
 	esac
 fi
+
